name: "Github Tag"
description: "Update the provided tag in the Github repo"
author: "Richard Simko"
inputs:
  github_token:
    description: "Required for permission to tag the repo."
    required: true
  tag_name:
    description: "Name of tag to be used"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "git-merge"
  color: "purple"
