name: CI
on:
  push

jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag name
        id: extract-tag
        run: |
          TAG_NAME=${GITHUB_REF//\//-}
          echo "TAG_NAME=test-${TAG_NAME}" >> $GITHUB_OUTPUT
      - name: Update test tag
        uses: ./
        with:
          tag_name: ${{ steps.extract-tag.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove test tag
        run: |
          git tag -d ${{ steps.extract-tag.outputs.TAG_NAME }}
          git push --delete origin ${{ steps.extract-tag.outputs.TAG_NAME }}
