name: Update version reference
on:
  push

jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/tags/v1.0.7
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - name: Extract major version from tag
        id: extract-version
        run: |
          FULL_VERSION=${GITHUB_REF##*/}
          MAJOR_VERSION=$(echo "${FULL_VERSION%.*.*}")
          echo "tag_name=${MAJOR_VERSION}" >> $GITHUB_OUTPUT
      - name: Update reference to latest version
        uses: ./
        with:
          tag_name: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
